---
- name: Import RabbitMQ GPG signing key
  apt_key:
    url: "{{ rabbitmq_deb_gpg_url }}"
    state: present
    validate_certs: false
  register: _add_apt_key
  until: _add_apt_key is succeeded
  retries: 5
  delay: 2

- name: Add RabbitMQ repository
  template:
    src: "{{ rabbitmq_deb_repo_tpl }}"
    dest: >
      "/etc/apt/sources.list.d/
      {{ rabbitmq_deb_repo_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    mode: 0644
    backup: true

- name: Add RabbitMQ repository pinning preferences
  template:
    src: "{{ rabbitmq_deb_pinning_tpl }}"
    dest: >
      "/etc/apt/preferences.d/
      {{ rabbitmq_deb_pinning_tpl | basename | regex_replace('\\.j2$', '') }}"
    force: true
    mode: 0644
    backup: true

- name: Update cache
  apt:
    update_cache: true
  changed_when: false

- name: Install RabbitMQ
  apt:
    package: >
      "rabbitmq-server{{ rabbitmq_series_deb_version |
      ternary ('=' + (rabbitmq_series_deb_version | string),'') }}"
    state: present
