---
- name: Allow localhost default port
  ansible.builtin.iptables:
    chain: INPUT
    action: append
    protocol: tcp
    source: localhost
    destination_port: 5672
    jump: ACCEPT

- name: Drop traffic on the default port
  ansible.builtin.iptables:
    chain: INPUT
    action: append
    protocol: tcp
    destination_port: 5672
    jump: DROP
