---
- name: Allow public access to the console
  ansible.builtin.iptables:
    chain: INPUT
    action: insert
    protocol: tcp
    source: localhost
    destination_port: 15672
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT

- name: Allow localhost default port
  ansible.builtin.iptables:
    chain: INPUT
    action: append
    protocol: tcp
    source: localhost
    destination_port: 5672
    jump: ACCEPT

- name: Drop traffic on the default port
  ansible.builtin.iptables:
    chain: INPUT
    action: append
    protocol: tcp
    destination_port: 5672
    jump: DROP
