---
- name: Install Erlang
  import_tasks: install_erlang.yml

- name: Install and configure Rabbitmq service
  import_tasks: install_rabbitmq.yml

- name: Install and configure Rabbitmq service
  import_tasks: configure_rabbitmq.yml

- name: Configure network
  import_tasks: iptables.yml

- name: Ensure that pika is installed
  pip:
    name: pika

- name: Install yamllint
  apt:
    package: yamllint

- name: Execute publisher script
  script: publish.py
  args:
    executable: python3
